### ISSUE TITLE
Subgroups feature

### ISSUE THREAD

**Issue by Ginden** [neoliberal/user_pinger#29]
I was thinking about adding feature of "subgroups".

Eg. users can subscribe to `USA:KENTUCKY` group without subscribing to whole `USA`, or `GAMING:FPS`. 

But I would like to ask if it's useful, before implementing it and creating pull request.

**Comment by jenbanim** [comment]
I've thought about this before, and while it's definitely a cool idea, I think it's too confusing and there are better solutions that accomplish mostly the same thing. Here's some examples why, using USA-WA as a subgroup of USA as an example:

Lets say someone pings the USA group, and a new user decides they want to subscribe. Based on the name, they'd likely expect that they'd receive messages about national news and politics, and they would be annoyed when they receive state news pings from subgroups like USA-WA

Likewise, if someone is subscribed to USA-WA, they might be annoyed when they receive pings for the USA group, since they're less relevant. They might then try to unsubscribe from the USA ping and get really confused when the bot says that they're not a member

These aren't insurmountable problems, but I want the bot's behavior to be extremely intuitive, and there are enough difficulties with this system that I believe the underlying issue is better solved through other features. Specifically, I'm planning on making it possible to ping multiple groups (#9). The main benefit of subgroups (imo) is being able to ping a parent group and reach all of the subgroups at once. Multiple pings does basically the same thing, but in a more flexible manner, since it doesn't rely on a static group structure
